HelloWorld/HelloWorld/Models/Kategori.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HelloWorld.Models
{
    public class Kategori
    {
        public int Id { get; set; }
        public string KategoriAdı { get; set; }
    }
}

HelloWorld/HelloWorld/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HelloWorld.Models
{
    public class Product
    {
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string Aciklama { get; set; }
        public double fiyat { get; set; }
        public bool Satistami { get; set; }
    }
}

HelloWorld/HelloWorld/Models/UrunKategoriModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HelloWorld.Models
{
    public class UrunKategoriModel
    {
        public int UrunSayisi { get; set; }
        public List<Product> Urunler { get; set; }
    }
}

HelloWorld/HelloWorld/Controllers/HomeController.cs
using HelloWorld.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//Kullanıcın isteklerinin karşılandığı yer controller'dır istek karşılandıktan sonra kullanılaraca kaynak sunuluyor bir html sayfası sunulabilir mesela
//isteğin türü ise controller içerisindeki action metotlarıyla karşılanıyor
//uygulama ilk çalıştığında varsayılan olarak HomeContoller altındaki İndex actionu çalıştırılır bu ayar App_Start altındaki RouteConfig'de tutuluyor
namespace HelloWorld.Controllers
{
    //veritabanına bağlanır ve bilgileri getirir.
    //getirilen bilgiler bir model içerisine yani bir sınıf içerisine aktarılır ve bu model view'e gönderilir
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            //bu şekilde bu diziyi ilgili cshtml dosyasına göndermiş olduk ancak index.cshtml 'ninde kendisine gönderilen bilgiden haberi olması gerekiyor yani cshtml sayfasının bir modeli olması gerekiyor
            //Model kavramını kullanarak bu şekilde controller'dan view üzerine bir bilgi taşıdık
            //string[] kurslar = { "Mvc kursu", "web form kursu", "c# kursu" };
            //return View(kurslar);

            //model sınıfı oluşturduktan sonra
            //bu Model katmanından tanımlamış olduğum ürün listesini view üzerine göndericem
            //ilgili view model olarak bunu beklemesi gerekiyor
            List<Product> urunler = new List<Product>()
            {
                new Product(){UrunId=1,UrunAdi="Samsung S6",Aciklama="İdare eder",fiyat=1000,Satistami=true},
                new Product(){UrunId=2,UrunAdi="Samsung S7",Aciklama="İdare eder",fiyat=2000,Satistami=false},
                new Product(){UrunId=3,UrunAdi="Samsung S8",Aciklama="İdare eder",fiyat=3000,Satistami=true},
                new Product(){UrunId=4,UrunAdi="Iphone 6",Aciklama="İdare eder",fiyat=3000,Satistami=false},
                new Product(){UrunId=5,UrunAdi="Iphone 7",Aciklama="İdare eder",fiyat=4000,Satistami=true},
            };
            //bu listenin yanında ekstra bir bilgi göndermek istiyorsak veya ikinci bir liste göndermek istiyorsak view'a bu sefer ViewBag kullanırız sayfanın modeli tek bir tane olabilir dolayısıyla viewbag ile gönderiyoruz
            //UrunKategoriModel modeli oluşturulduktan sonra
            UrunKategoriModel model = new UrunKategoriModel();
            model.Urunler = urunler;
            model.UrunSayisi = urunler.Count();

            ViewBag.UrunSayisi = urunler.Count();
            return View(model);
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
    }
}

HelloWorld/HelloWorld/Controllers/KategoriController.cs
using HelloWorld.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelloWorld.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        public ActionResult Index()
        {
            return View();
        }
        //partialView'in action  metotu ile otomatik çalışan partialview'ler oluşturulabilir
        //ChildActionOnly ile sadece içerisinde bulunduğu view içerisinden çağırılabiliyor
        [ChildActionOnly]
        public PartialViewResult KategoriMenu()
        {
            List<Kategori> kategoriler = new List<Kategori>()
            {
                new Kategori(){KategoriAdı="Telefonlar",Id=1},
                new Kategori(){KategoriAdı="Tabletler",Id=2},
                new Kategori(){KategoriAdı="Laptoplar",Id=3}
            };
            return PartialView("KategoriMenu",kategoriler);
        }
    }
}

HelloWorld/HelloWorld/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelloWorld.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }
        public ActionResult Details()
        {
            return View();
        }
    }
}

HelloWorld/HelloWorld/Views/Home/About.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>About</title>
</head>
<body>
    <div> 
        About.
    </div>
</body>
</html>

HelloWorld/HelloWorld/Views/Home/Contact.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Contact</title>
</head>
<body>
    <div> 
        Contact.
    </div>
</body>
</html>

HelloWorld/HelloWorld/Views/Home/Index.cshtml
@*index.cshtml 'ninde kendisine gönderilen bilgiden haberi olması gerekiyor yani cshtml sayfasının bir modeli olması gerekiyor*@
@*@model string[]*@

@*model sınıfı oluşturduktan sonra*@
@*@model List<HelloWorld.Models.Product>*@

@* UrunKategoriModel modeli oluşturulduktan sonra *@
@model HelloWorld.Models.UrunKategoriModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @foreach (var kurs in Model.Urunler)
        {
            @kurs.UrunAdi
            @kurs.UrunId
            @kurs.Aciklama
            @kurs.fiyat
            @kurs.Satistami
        }

      @* partial view'i kullanmak *@
        @*@Html.Partial("KategoriMenu",Model.Kategoriler)*@

        @* otomaik partial view'i kullanmak birinci parametrede action ismi ikinci parametrede controller ismi *@
        @*@Html.Action("KategoriMenu", "Kategori");*@

    </div>
    @* ViewBag kullanmak *@,
    @*@ViewBag.UrunSayisi
    @foreach (var kategori in (List<HelloWorld.Models.Kategori>)ViewBag.Kategoriler)
    {
        @kategori.Id
        @kategori.KategoriAdı
    }*@
</body>
</html>